// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4c81d17e8de07f650cddf73ce751ba8d)
declare namespace Cloudflare {
	interface Env {
		DATURA_CHANNELS: DurableObjectNamespace<import("./src/index").DaturaChannelDO>;
		// Environment variables
		KEY_ROTATION_HOURS?: string;
		EPHEMERAL_MESSAGE_DEFAULT_TTL?: string;
		MAX_MESSAGE_CACHE?: string;
	}
}
interface Env extends Cloudflare.Env {}
